spring:
  application:
    name: iot-project-server
  datasource:
    url: jdbc:postgresql://localhost:5432/iot
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true
  devtools:
    remote:
      restart:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health